name: Release Schedule

on:
  schedule:
    - cron: "0 0 * * 0" # Every Sunday at 00:00 UTC

permissions: {}

jobs:
  schedule:
    runs-on: ubuntu-latest
    steps:
      - run: |
          gh release create "$(date -Idate)" \
            --repo SlashNephy/TVTest-builder \
            --generate-notes
        env:
          GITHUB_TOKEN: ${{ secrets.BOT_GITHUB_TOKEN }}
